# Generated by Django 5.0.6 on 2024-05-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('national_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('balance', models.FloatField()),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='usersImage/')),
                ('governorate', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('date_of_process', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='SB_app.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='SB_app.user')),
            ],
        ),
    ]
