# Generated by Django 4.2.7 on 2024-05-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0004_user_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_creation',
        ),
    ]
