# Generated by Django 4.2.7 on 2024-05-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0005_remove_user_date_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
