# Generated by Django 4.2.7 on 2024-05-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB_app', '0006_user_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_creation',
            field=models.CharField(blank=True, default='2024-05-26', max_length=100, null=True),
        ),
    ]
